from frappe.custom.doctype.custom_field.custom_field import create_custom_fields


def setup_custom_fields():
	custom_fields = {
		"Customer": [
			dict(
				fieldname="ntn",
				label="NTN / CNIC",
				fieldtype="Data",
				insert_after="customer_group",
			),
			dict(
				fieldname="address",
				label="Address",
				fieldtype="Data",
				insert_after="ntn",
			),
			dict(
				fieldname="province",
				label="Province",
				fieldtype="Select",
				options="PUNJAB\nBALOCHISTAN\nAZAD JAMMU AND KASHMIR\nCAPITAL TERRITORY\nKHYBER PAKHTUNKHWA\nSINDH\nGILGIT BALTISTAN",
				insert_after="address",
			),
			dict(
				fieldname="registration_type",
				label="Registration Type",
				fieldtype="Select",
				options="Registered\nUnregistered",
				insert_after="province",
			),
			dict(
				fieldname="enable_digital_invoicing",
				label="Enable Digital Invoicing",
				fieldtype="Check",
				insert_after="registration_type",
			),
		],
		"Supplier": [
			dict(
				fieldname="address",
				label="Address",
				fieldtype="Data",
				insert_after="country",
			),
			dict(
				fieldname="province",
				label="Province",
				fieldtype="Select",
				options="PUNJAB\nBALOCHISTAN\nAZAD JAMMU AND KASHMIR\nCAPITAL TERRITORY\nKHYBER PAKHTUNKHWA\nSINDH\nGILGIT BALTISTAN",
				insert_after="address",
			),
			dict(
				fieldname="registration_type",
				label="Registration Type",
				fieldtype="Select",
				options="Registered\nUnregistered",
				insert_after="province",
			),
		],
		"Company": [
			dict(
				fieldname="di_settings_tab",
				label="FBR Settings",
				fieldtype="Tab Break",
				insert_after="old_parent",
			),
			dict(
				fieldname="address",
				label="Address",
				fieldtype="Data",
				insert_after="di_settings_tab",
			),
			dict(
				fieldname="province",
				label="Province",
				fieldtype="Select",
				options="PUNJAB\nBALOCHISTAN\nAZAD JAMMU AND KASHMIR\nCAPITAL TERRITORY\nKHYBER PAKHTUNKHWA\nSINDH\nGILGIT BALTISTAN",
				insert_after="address",
			),
			dict(
				fieldname="strn_no",
				label="STRN No",
				fieldtype="Data",
				insert_after="province",
			),
			dict(
				fieldname="sale_types",
				label="Sale Types",
				fieldtype="Table",
				options="Company Sales Type",
				insert_after="strn_no",
			),
		],
		"Item": [
			dict(
				fieldname="tab_di_settings",
				label="DI Settings",
				fieldtype="Tab Break",
				insert_after="uoms",
			),
			dict(
				fieldname="hs_code",
				label="HS Code",
				fieldtype="Link",
				options="HS Code",
				insert_after="tab_di_settings",
			),
			dict(
				fieldname="hs_uom",
				label="HS UOM",
				fieldtype="Link",
				options="HS Uom",
				insert_after="hs_code",
				read_only=1,
				fetch_from="hs_code.uom",
			),
			dict(
				fieldname="column_break_di_setting",
				fieldtype="Column Break",
				insert_after="hs_uom",
			),
			dict(
				fieldname="sales_type",
				label="Sale Type",
				fieldtype="Link",
				options="Sales Type",
				insert_after="column_break_di_setting",
			),
			dict(
				fieldname="sro_item_serial_no",
				label="SRO Item Serial No",
				fieldtype="Data",
				insert_after="sales_type",
			),
			dict(
				fieldname="sro_schedule_no",
				label="SRO Schedule No",
				fieldtype="Data",
				insert_after="sro_item_serial_no",
			),
		],
		"Sales Invoice": [
			dict(
				fieldname="di_section",
				label="Digital Invoicing",
				fieldtype="Section Break",
				insert_after="remarks",
				depends_on="eval:!doc.is_pos",
			),
			dict(
				fieldname="integration_id",
				label="FBR Invoice Number",
				fieldtype="Read Only",
				insert_after="di_section",
			),
			dict(
				fieldname="is_posted",
				label="Posted to DI",
				fieldtype="Check",
				insert_after="integration_id",
				read_only=1,
			),
			dict(
				fieldname="column_break_di",
				fieldtype="Column Break",
				insert_after="is_posted",
			),
			dict(
				fieldname="posting_datetime",
				label="DI Posting Datetime",
				fieldtype="Datetime",
				insert_after="column_break_di",
				read_only=1,
			),
			dict(
				fieldname="di_invoice_type",
				label="DI Invoice Type",
				fieldtype="Select",
				options="Sale Invoice\nDebit Note",
				insert_after="posting_datetime",
				read_only=1,
			),
			dict(
				fieldname="di_scenario_id",
				label="Sandbox Scenario",
				fieldtype="Link",
				options="Sandbox Scenario",
				insert_after="di_invoice_type",
			),
		],
		"Sales Invoice Item": [
			dict(
				fieldname="di_taxes_section",
				label="Digital Invoicing",
				fieldtype="Section Break",
				insert_after="grant_commission",
			),
			dict(
				fieldname="hs_code",
				label="HS Code",
				fieldtype="Link",
				options="HS Code",
				insert_after="di_taxes_section",
				fetch_from="item_code.hs_code",
				read_only=1,
				allow_on_submit=1,
			),
			dict(
				fieldname="hs_uom",
				label="HS UOM",
				fieldtype="Link",
				options="HS Uom",
				insert_after="hs_code",
				fetch_from="item_code.hs_uom",
				read_only=1,
				allow_on_submit=1,
			),
			dict(
				fieldname="sales_type",
				label="Sale Type",
				fieldtype="Link",
				options="Sales Type",
				insert_after="hs_uom",
				fetch_from="item_code.sales_type",
				allow_on_submit=1,
			),
			dict(
				fieldname="column_break_di_item",
				fieldtype="Column Break",
				insert_after="sales_type",
			),
			dict(
				fieldname="sro_serial_no",
				label="SRO Serial No",
				fieldtype="Read Only",
				insert_after="column_break_di_item",
				fetch_from="item_code.sro_item_serial_no",
			),
			dict(
				fieldname="schedule_no",
				label="SRO Schedule No",
				fieldtype="Read Only",
				insert_after="sro_serial_no",
				fetch_from="item_code.sro_schedule_no",
			),
			dict(
				fieldname="fed_payable",
				label="FED Payable",
				fieldtype="Currency",
				insert_after="schedule_no",
				default="0",
				allow_on_submit=1,
			),
		],
		"Purchase Invoice": [
			dict(
				fieldname="di_section",
				label="Digital Invoicing",
				fieldtype="Section Break",
				insert_after="remarks",
			),
			dict(
				fieldname="integration_id",
				label="FBR Invoice Number",
				fieldtype="Read Only",
				insert_after="di_section",
			),
			dict(
				fieldname="is_posted",
				label="Posted to DI",
				fieldtype="Check",
				insert_after="integration_id",
				read_only=1,
			),
			dict(
				fieldname="column_break_di_pi",
				fieldtype="Column Break",
				insert_after="is_posted",
			),
			dict(
				fieldname="posting_datetime",
				label="DI Posting Datetime",
				fieldtype="Datetime",
				insert_after="column_break_di_pi",
				read_only=1,
			),
		],
		"Purchase Invoice Item": [
			dict(
				fieldname="hs_code",
				label="HS Code",
				fieldtype="Read Only",
				insert_after="item_name",
				fetch_from="item_code.hs_code",
			),
			dict(
				fieldname="hs_uom",
				label="HS UOM",
				fieldtype="Link",
				options="HS Uom",
				insert_after="hs_code",
				fetch_from="item_code.hs_uom",
				read_only=1,
				allow_on_submit=1,
			),
			dict(
				fieldname="sales_type",
				label="Sale Type",
				fieldtype="Link",
				options="Sales Type",
				insert_after="hs_uom",
				fetch_from="item_code.sales_type",
				allow_on_submit=1,
			),
			dict(
				fieldname="column_break_di_pi_item",
				fieldtype="Column Break",
				insert_after="sales_type",
			),
			dict(
				fieldname="sro_serial_no",
				label="SRO Serial No",
				fieldtype="Data",
				insert_after="column_break_di_pi_item",
				fetch_from="item_code.sro_item_serial_no",
				read_only=1,
				allow_on_submit=1,
			),
			dict(
				fieldname="schedule_no",
				label="SRO Schedule No",
				fieldtype="Data",
				insert_after="sro_serial_no",
				fetch_from="item_code.sro_schedule_no",
				read_only=1,
				allow_on_submit=1,
			),
			dict(
				fieldname="fed_payable",
				label="FED Payable",
				fieldtype="Currency",
				insert_after="schedule_no",
				default="0",
				allow_on_submit=1,
			),
		],
		"Sales Taxes and Charges": [
			dict(
				label="Tax Type",
				fieldname="tax_type",
				fieldtype="Select",
				insert_after="account_head",
				options="Sales Tax\nFurther Tax\nAdvance Tax",
				in_list_view=1,
			),
		],
	}

	create_custom_fields(custom_fields)
